name: smart_learn
description: Application d'apprentissage intelligent avec IA

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.6.0
  confetti: ^0.7.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.2

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6

  # Requêtes HTTP
  http: ^1.1.0

  # Stockage local
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  youtube_player_flutter: ^9.0.3  # Player YouTube intégré
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  # ✅ NOUVEAU : Gestion du thèm
  provider: ^6.1.1
  # ✅ Internationalisation
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
  # ✅ NOUVEAU : Génération des traductions
  generate: true

  # Si vous avez des assets
  # assets:
  #   - assets/google_logo.png
  #   - assets/images/

  # Fonts personnalisées (optionnel)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700